### ISSUE TITLE
improper handling of PNGs? Zend Studio 10.x

### ISSUE THREAD

**Issue by jackdpeterson** [davidglevy/eclipse-icon-enlarger#4]
2014-06-23 15:00:59 ERROR FixIcons:214 - Unable to scale [icons/ignore-all-disabled.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:00:59 ERROR FixIcons:214 - Unable to scale [icons/ignore-file-disabled.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:00:59 ERROR FixIcons:214 - Unable to scale [icons/ignore-project-disabled.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:00:59 ERROR FixIcons:214 - Unable to scale [icons/ignore-this-disabled.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:09 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/express/node_modules/connect/lib/public/icons/page_white.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:09 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/express/node_modules/connect/lib/public/icons/page_white_copy.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:09 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/express/node_modules/connect/lib/public/icons/page_white_gear.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:09 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/express/node_modules/connect/lib/public/icons/page_white_horizontal.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:10 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/express/node_modules/connect/lib/public/icons/page_white_stack.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:10 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/express/node_modules/connect/lib/public/icons/page_white_text.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:10 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/express/node_modules/connect/lib/public/icons/page_white_text_width.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:10 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/express/node_modules/connect/lib/public/icons/page_white_width.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:10 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/express/node_modules/connect/lib/public/icons/page_white_zip.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:15 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib/public/icons/page_white.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:15 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib/public/icons/page_white_copy.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:15 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib/public/icons/page_white_gear.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:15 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib/public/icons/page_white_horizontal.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:15 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib/public/icons/page_white_stack.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:15 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib/public/icons/page_white_text.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:15 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib/public/icons/page_white_text_width.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:15 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib/public/icons/page_white_width.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:15 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib/public/icons/page_white_zip.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:15 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib-cov/public/icons/page_white.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:15 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib-cov/public/icons/page_white_copy.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:15 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib-cov/public/icons/page_white_gear.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:15 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib-cov/public/icons/page_white_horizontal.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:16 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib-cov/public/icons/page_white_stack.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:16 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib-cov/public/icons/page_white_text.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:16 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib-cov/public/icons/page_white_text_width.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:16 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib-cov/public/icons/page_white_width.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:01:16 ERROR FixIcons:214 - Unable to scale [nodejs/node_modules/cordova/node_modules/ripple-emulator/node_modules/express/node_modules/connect/lib-cov/public/icons/page_white_zip.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:03:43 ERROR FixIcons:214 - Unable to scale [glyphicons-halflings.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:152)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:05:32 ERROR FixIcons:214 - Unable to scale [images/org.eclipse.ui.externaltools/clcl16/remove_co.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:06:15 ERROR FixIcons:214 - Unable to scale [skin/classic/global/icons/autoscroll.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:06:16 ERROR FixIcons:214 - Unable to scale [skin/classic/global/toolbar/Lighten.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:06:16 ERROR FixIcons:214 - Unable to scale [skin/classic/global/toolbar/spring.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:06:17 ERROR FixIcons:214 - Unable to scale [skin/classic/aero/global/toolbar/Lighten.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:06:17 ERROR FixIcons:214 - Unable to scale [skin/classic/aero/global/toolbar/spring.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)
2014-06-23 15:06:29 ERROR FixIcons:214 - Unable to scale [resources/ZendSkeletonApplication/public/img/glyphicons-halflings.png]: Unknown image type 0
java.lang.IllegalArgumentException: Unknown image type 0
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
    at testEclipse.FixIcons.processImage(FixIcons.java:201)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:130)
    at testEclipse.FixIcons.processDirectory(FixIcons.java:104)
    at testEclipse.FixIcons.main(FixIcons.java:84)

**Comment by garganti** [comment]
I followed the suggestions given here:
http://stackoverflow.com/questions/5836128/how-do-i-make-javas-imagebuffer-to-read-a-png-file-correctly
and with:
int imageType = croppedImage.getType();
if(imageType == 0) imageType = 5;
I no longer have this kind of error.
I still have some errors though. Probably it is not enough.

**Comment by Akuka** [comment]
change line 201 from:
                    new BufferedImage(outWidth, outHeight, out.getType()));
to:
                    new BufferedImage(outWidth, outHeight, ( out.getType() == 0 ? 5 : out.getType() )));

**Comment by chrisphe** [comment]
The simple fix is to change their image type to 5. But also take a look at the pull request #5 I submitted which also addresses this.
